# Generated by Django 6.0.7 on 2026-08-05 10:15

import coupons.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('large_order_subtotal_threshold', models.PositiveIntegerField(default=200000)),
                ('large_order_delivery_threshold', models.PositiveIntegerField(default=100000)),
                ('large_order_coupon_amount', models.PositiveIntegerField(default=15000)),
                ('first_order_min_total', models.PositiveIntegerField(default=30000)),
                ('first_order_discount', models.PositiveIntegerField(default=5000)),
                ('points_per_delivery_unit', models.PositiveIntegerField(default=10)),
                ('delivery_unit_size', models.PositiveIntegerField(default=10000)),
                ('points_redemption_value', models.PositiveIntegerField(default=100)),
                ('points_redemption_minimum', models.PositiveIntegerField(default=150)),
            ],
            options={
                'verbose_name': 'Promotion Config',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=coupons.models._generate_coupon_code, max_length=20, unique=True)),
                ('coupon_type', models.CharField(choices=[('large_order', 'Large Order Reward'), ('first_order', 'First Order Discount'), ('manual', 'Manual / Admin')], default='manual', max_length=20)),
                ('discount', models.PositiveIntegerField(help_text='Discount amount in UGX')),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('usage_limit', models.PositiveIntegerField(default=1)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='If set, only this user can use the coupon', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_balance', models.IntegerField(default=0)),
                ('points_earned', models.IntegerField(default=0)),
                ('points_redeemed', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('tx_type', models.CharField(choices=[('earn', 'Earned'), ('redeem', 'Redeemed'), ('reverse', 'Reversed')], max_length=10)),
                ('points', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='coupons.loyaltyaccount')),
            ],
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='coupons.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('coupon', 'user')},
            },
        ),
    ]
