# Generated by Django 6.0.7 on 2026-07-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatmessage_is_edited_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='file_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('doc', 'Document')], default='', max_length=10),
        ),
    ]
