# Generated by Django 6.0.7 on 2026-07-10 14:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='crud_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
