# Generated by Django 5.2.8 on 2026-08-01 09:11

from django.db import migrations, models


def backfill_phone(apps, schema_editor):
    """Give every user with a blank/duplicate phone a unique placeholder."""
    User = apps.get_model('accounts', 'User')
    seen = set()
    for user in User.objects.all().order_by('id'):
        phone = (user.phone or '').strip()
        if not phone or phone in seen:
            phone = f"unknown_{user.id}"
        seen.add(phone)
        if user.phone != phone:
            user.phone = phone
            user.save(update_fields=['phone'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_email_alter_user_phone'),
    ]

    operations = [
        migrations.RunPython(backfill_phone, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
