# Generated by Django 6.0.7 on 2026-07-10 14:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='user_crud_number',
            field=models.UUIDField(db_index=True, editable=False, null=True),
        ),
    ]
