# Generated by Django 6.0.7 on 2026-07-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('rate_product', 'Rate Product'), ('order_update', 'Order Update'), ('welcome', 'Welcome')], max_length=30),
        ),
    ]
