# Generated by Django 6.0.7 on 2026-07-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('rate_product', 'Rate Product'), ('order_update', 'Order Update'), ('welcome', 'Welcome'), ('return_update', 'Return Update')], max_length=30),
        ),
    ]
