# Generated by Django 6.0.7 on 2026-07-12 18:36

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Delivery charge in UGX', max_digits=10),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='products/'),
        ),
    ]
